Traceback (most recent call last):
  File "/home/runner/micromamba/envs/bids23/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/micromamba/envs/bids23/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/bids23/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/bids23/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/bids23/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/micromamba/envs/bids23/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/micromamba/envs/bids23/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import geopandas as gpd
try:
    GAUL = gpd.read_file('Italy.geojson')
except:
    GAUL = gpd.read_file('zip+https://mars.jrc.ec.europa.eu/asap/files/gaul1_asap.zip') 

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mCPLE_OpenFailedError[0m                      Traceback (most recent call last)
File [0;32mfiona/ogrext.pyx:136[0m, in [0;36mfiona.ogrext.gdal_open_vector[0;34m()[0m

File [0;32mfiona/_err.pyx:291[0m, in [0;36mfiona._err.exc_wrap_pointer[0;34m()[0m

[0;31mCPLE_OpenFailedError[0m: Italy.geojson: No such file or directory

During handling of the above exception, another exception occurred:

[0;31mDriverError[0m                               Traceback (most recent call last)
Cell [0;32mIn[12], line 3[0m
[1;32m      2[0m [38;5;28;01mtry[39;00m:
[0;32m----> 3[0m     GAUL [38;5;241m=[39m [43mgpd[49m[38;5;241;43m.[39;49m[43mread_file[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mItaly.geojson[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      4[0m [38;5;28;01mexcept[39;00m:

File [0;32m~/micromamba/envs/bids23/lib/python3.11/site-packages/geopandas/io/file.py:297[0m, in [0;36m_read_file[0;34m(filename, bbox, mask, rows, engine, **kwargs)[0m
[1;32m    295[0m         path_or_bytes [38;5;241m=[39m filename
[0;32m--> 297[0m     [38;5;28;01mreturn[39;00m [43m_read_file_fiona[49m[43m([49m
[1;32m    298[0m [43m        [49m[43mpath_or_bytes[49m[43m,[49m[43m [49m[43mfrom_bytes[49m[43m,[49m[43m [49m[43mbbox[49m[38;5;241;43m=[39;49m[43mbbox[49m[43m,[49m[43m [49m[43mmask[49m[38;5;241;43m=[39;49m[43mmask[49m[43m,[49m[43m [49m[43mrows[49m[38;5;241;43m=[39;49m[43mrows[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m
[1;32m    299[0m [43m    [49m[43m)[49m
[1;32m    301[0m [38;5;28;01melse[39;00m:

File [0;32m~/micromamba/envs/bids23/lib/python3.11/site-packages/geopandas/io/file.py:338[0m, in [0;36m_read_file_fiona[0;34m(path_or_bytes, from_bytes, bbox, mask, rows, where, **kwargs)[0m
[1;32m    337[0m [38;5;28;01mwith[39;00m fiona_env():
[0;32m--> 338[0m     [38;5;28;01mwith[39;00m [43mreader[49m[43m([49m[43mpath_or_bytes[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m [38;5;28;01mas[39;00m features:
[1;32m    339[0m         crs [38;5;241m=[39m features[38;5;241m.[39mcrs_wkt

File [0;32m~/micromamba/envs/bids23/lib/python3.11/site-packages/fiona/env.py:457[0m, in [0;36mensure_env_with_credentials.<locals>.wrapper[0;34m(*args, **kwds)[0m
[1;32m    456[0m [38;5;28;01mwith[39;00m env_ctor(session[38;5;241m=[39msession):
[0;32m--> 457[0m     [38;5;28;01mreturn[39;00m [43mf[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwds[49m[43m)[49m

File [0;32m~/micromamba/envs/bids23/lib/python3.11/site-packages/fiona/__init__.py:292[0m, in [0;36mopen[0;34m(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, allow_unsupported_drivers, **kwargs)[0m
[1;32m    291[0m [38;5;28;01mif[39;00m mode [38;5;129;01min[39;00m ([38;5;124m"[39m[38;5;124ma[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mr[39m[38;5;124m"[39m):
[0;32m--> 292[0m     colxn [38;5;241m=[39m [43mCollection[49m[43m([49m
[1;32m    293[0m [43m        [49m[43mpath[49m[43m,[49m
[1;32m    294[0m [43m        [49m[43mmode[49m[43m,[49m
[1;32m    295[0m [43m        [49m[43mdriver[49m[38;5;241;43m=[39;49m[43mdriver[49m[43m,[49m
[1;32m    296[0m [43m        [49m[43mencoding[49m[38;5;241;43m=[39;49m[43mencoding[49m[43m,[49m
[1;32m    297[0m [43m        [49m[43mlayer[49m[38;5;241;43m=[39;49m[43mlayer[49m[43m,[49m
[1;32m    298[0m [43m        [49m[43menabled_drivers[49m[38;5;241;43m=[39;49m[43menabled_drivers[49m[43m,[49m
[1;32m    299[0m [43m        [49m[43mallow_unsupported_drivers[49m[38;5;241;43m=[39;49m[43mallow_unsupported_drivers[49m[43m,[49m
[1;32m    300[0m [43m        [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m
[1;32m    301[0m [43m    [49m[43m)[49m
[1;32m    302[0m [38;5;28;01melif[39;00m mode [38;5;241m==[39m [38;5;124m"[39m[38;5;124mw[39m[38;5;124m"[39m:

File [0;32m~/micromamba/envs/bids23/lib/python3.11/site-packages/fiona/collection.py:243[0m, in [0;36mCollection.__init__[0;34m(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, include_fields, wkt_version, allow_unsupported_drivers, **kwargs)[0m
[1;32m    242[0m     [38;5;28mself[39m[38;5;241m.[39msession [38;5;241m=[39m Session()
[0;32m--> 243[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msession[49m[38;5;241;43m.[39;49m[43mstart[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    244[0m [38;5;28;01melif[39;00m [38;5;28mself[39m[38;5;241m.[39mmode [38;5;129;01min[39;00m ([38;5;124m"[39m[38;5;124ma[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mw[39m[38;5;124m"[39m):

File [0;32mfiona/ogrext.pyx:588[0m, in [0;36mfiona.ogrext.Session.start[0;34m()[0m

File [0;32mfiona/ogrext.pyx:143[0m, in [0;36mfiona.ogrext.gdal_open_vector[0;34m()[0m

[0;31mDriverError[0m: Italy.geojson: No such file or directory

During handling of the above exception, another exception occurred:

[0;31mCPLE_OpenFailedError[0m                      Traceback (most recent call last)
File [0;32mfiona/ogrext.pyx:136[0m, in [0;36mfiona.ogrext.gdal_open_vector[0;34m()[0m

File [0;32mfiona/_err.pyx:291[0m, in [0;36mfiona._err.exc_wrap_pointer[0;34m()[0m

[0;31mCPLE_OpenFailedError[0m: '/vsizip/vsicurl/https://mars.jrc.ec.europa.eu/asap/files/gaul1_asap.zip' does not exist in the file system, and is not recognized as a supported dataset name.

During handling of the above exception, another exception occurred:

[0;31mDriverError[0m                               Traceback (most recent call last)
Cell [0;32mIn[12], line 5[0m
[1;32m      3[0m     GAUL [38;5;241m=[39m gpd[38;5;241m.[39mread_file([38;5;124m'[39m[38;5;124mItaly.geojson[39m[38;5;124m'[39m)
[1;32m      4[0m [38;5;28;01mexcept[39;00m:
[0;32m----> 5[0m     GAUL [38;5;241m=[39m [43mgpd[49m[38;5;241;43m.[39;49m[43mread_file[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mzip+https://mars.jrc.ec.europa.eu/asap/files/gaul1_asap.zip[39;49m[38;5;124;43m'[39;49m[43m)[49m 

File [0;32m~/micromamba/envs/bids23/lib/python3.11/site-packages/geopandas/io/file.py:297[0m, in [0;36m_read_file[0;34m(filename, bbox, mask, rows, engine, **kwargs)[0m
[1;32m    294[0m     [38;5;28;01melse[39;00m:
[1;32m    295[0m         path_or_bytes [38;5;241m=[39m filename
[0;32m--> 297[0m     [38;5;28;01mreturn[39;00m [43m_read_file_fiona[49m[43m([49m
[1;32m    298[0m [43m        [49m[43mpath_or_bytes[49m[43m,[49m[43m [49m[43mfrom_bytes[49m[43m,[49m[43m [49m[43mbbox[49m[38;5;241;43m=[39;49m[43mbbox[49m[43m,[49m[43m [49m[43mmask[49m[38;5;241;43m=[39;49m[43mmask[49m[43m,[49m[43m [49m[43mrows[49m[38;5;241;43m=[39;49m[43mrows[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m
[1;32m    299[0m [43m    [49m[43m)[49m
[1;32m    301[0m [38;5;28;01melse[39;00m:
[1;32m    302[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124munknown engine [39m[38;5;124m'[39m[38;5;132;01m{[39;00mengine[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m"[39m)

File [0;32m~/micromamba/envs/bids23/lib/python3.11/site-packages/geopandas/io/file.py:338[0m, in [0;36m_read_file_fiona[0;34m(path_or_bytes, from_bytes, bbox, mask, rows, where, **kwargs)[0m
[1;32m    335[0m     reader [38;5;241m=[39m fiona[38;5;241m.[39mopen
[1;32m    337[0m [38;5;28;01mwith[39;00m fiona_env():
[0;32m--> 338[0m     [38;5;28;01mwith[39;00m [43mreader[49m[43m([49m[43mpath_or_bytes[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m [38;5;28;01mas[39;00m features:
[1;32m    339[0m         crs [38;5;241m=[39m features[38;5;241m.[39mcrs_wkt
[1;32m    340[0m         [38;5;66;03m# attempt to get EPSG code[39;00m

File [0;32m~/micromamba/envs/bids23/lib/python3.11/site-packages/fiona/env.py:457[0m, in [0;36mensure_env_with_credentials.<locals>.wrapper[0;34m(*args, **kwds)[0m
[1;32m    454[0m     session [38;5;241m=[39m DummySession()
[1;32m    456[0m [38;5;28;01mwith[39;00m env_ctor(session[38;5;241m=[39msession):
[0;32m--> 457[0m     [38;5;28;01mreturn[39;00m [43mf[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwds[49m[43m)[49m

File [0;32m~/micromamba/envs/bids23/lib/python3.11/site-packages/fiona/__init__.py:292[0m, in [0;36mopen[0;34m(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, allow_unsupported_drivers, **kwargs)[0m
[1;32m    289[0m     path [38;5;241m=[39m parse_path(fp)
[1;32m    291[0m [38;5;28;01mif[39;00m mode [38;5;129;01min[39;00m ([38;5;124m"[39m[38;5;124ma[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mr[39m[38;5;124m"[39m):
[0;32m--> 292[0m     colxn [38;5;241m=[39m [43mCollection[49m[43m([49m
[1;32m    293[0m [43m        [49m[43mpath[49m[43m,[49m
[1;32m    294[0m [43m        [49m[43mmode[49m[43m,[49m
[1;32m    295[0m [43m        [49m[43mdriver[49m[38;5;241;43m=[39;49m[43mdriver[49m[43m,[49m
[1;32m    296[0m [43m        [49m[43mencoding[49m[38;5;241;43m=[39;49m[43mencoding[49m[43m,[49m
[1;32m    297[0m [43m        [49m[43mlayer[49m[38;5;241;43m=[39;49m[43mlayer[49m[43m,[49m
[1;32m    298[0m [43m        [49m[43menabled_drivers[49m[38;5;241;43m=[39;49m[43menabled_drivers[49m[43m,[49m
[1;32m    299[0m [43m        [49m[43mallow_unsupported_drivers[49m[38;5;241;43m=[39;49m[43mallow_unsupported_drivers[49m[43m,[49m
[1;32m    300[0m [43m        [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m
[1;32m    301[0m [43m    [49m[43m)[49m
[1;32m    302[0m [38;5;28;01melif[39;00m mode [38;5;241m==[39m [38;5;124m"[39m[38;5;124mw[39m[38;5;124m"[39m:
[1;32m    303[0m     colxn [38;5;241m=[39m Collection(
[1;32m    304[0m         path,
[1;32m    305[0m         mode,
[0;32m   (...)[0m
[1;32m    314[0m         [38;5;241m*[39m[38;5;241m*[39mkwargs
[1;32m    315[0m     )

File [0;32m~/micromamba/envs/bids23/lib/python3.11/site-packages/fiona/collection.py:243[0m, in [0;36mCollection.__init__[0;34m(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, include_fields, wkt_version, allow_unsupported_drivers, **kwargs)[0m
[1;32m    241[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mmode [38;5;241m==[39m [38;5;124m"[39m[38;5;124mr[39m[38;5;124m"[39m:
[1;32m    242[0m     [38;5;28mself[39m[38;5;241m.[39msession [38;5;241m=[39m Session()
[0;32m--> 243[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msession[49m[38;5;241;43m.[39;49m[43mstart[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    244[0m [38;5;28;01melif[39;00m [38;5;28mself[39m[38;5;241m.[39mmode [38;5;129;01min[39;00m ([38;5;124m"[39m[38;5;124ma[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mw[39m[38;5;124m"[39m):
[1;32m    245[0m     [38;5;28mself[39m[38;5;241m.[39msession [38;5;241m=[39m WritingSession()

File [0;32mfiona/ogrext.pyx:588[0m, in [0;36mfiona.ogrext.Session.start[0;34m()[0m

File [0;32mfiona/ogrext.pyx:143[0m, in [0;36mfiona.ogrext.gdal_open_vector[0;34m()[0m

[0;31mDriverError[0m: '/vsizip/vsicurl/https://mars.jrc.ec.europa.eu/asap/files/gaul1_asap.zip' does not exist in the file system, and is not recognized as a supported dataset name.

